export const PUBLICATION_REQUEST = '@publication/PUBLICATION_REQUEST';
export const PUBLICATION_SUCCESS = '@publication/PUBLICATION_SUCCESS';
export const PUBLICATION_FAILURE = '@publication/PUBLICATION_FAILURE';

export const PUBLICATIONS_REQUEST = '@publication/PUBLICATIONS_REQUEST';
export const PUBLICATIONS_SUCCESS = '@publication/PUBLICATIONS_SUCCESS';
export const PUBLICATIONS_FAILURE = '@publication/PUBLICATIONS_FAILURE';

export const PUBLICATION_CREATE_REQUEST =
  '@publication/PUBLICATION_CREATE_REQUEST';
export const PUBLICATION_CREATE_SUCCESS =
  '@publication/PUBLICATION_CREATE_SUCCESS';
export const PUBLICATION_CREATE_FAILURE =
  '@publication/PUBLICATION_CREATE_FAILURE';

export const PUBLICATION_UPDATE_REQUEST =
  '@publication/PUBLICATION_UPDATE_REQUEST';
export const PUBLICATION_UPDATE_SUCCESS =
  '@publication/PUBLICATION_UPDATE_SUCCESS';
export const PUBLICATION_UPDATE_FAILURE =
  '@publication/PUBLICATION_UPDATE_FAILURE';

export const PUBLICATION_ACTIVATE_REQUEST =
  '@publication/PUBLICATION_ACTIVATE_REQUEST';
export const PUBLICATION_ACTIVATE_SUCCESS =
  '@publication/PUBLICATION_ACTIVATE_SUCCESS';
export const PUBLICATION_ACTIVATE_FAILURE =
  '@publication/PUBLICATION_ACTIVATE_FAILURE';

export const PUBLICATION_DEACTIVATE_REQUEST =
  '@publication/PUBLICATION_DEACTIVATE_REQUEST';
export const PUBLICATION_DEACTIVATE_SUCCESS =
  '@publication/PUBLICATION_DEACTIVATE_SUCCESS';
export const PUBLICATION_DEACTIVATE_FAILURE =
  '@publication/PUBLICATION_DEACTIVATE_FAILURE';
