export const USER_CREATE_REQUEST = '@user/USER_CREATE_REQUEST';
export const USER_CREATE_SUCCESS = '@user/USER_CREATE_SUCCESS';
export const USER_CREATE_FAILURE = '@user/USER_CREATE_FAILURE';

export const USER_UPDATE_REQUEST = '@user/USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = '@user/USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = '@user/USER_UPDATE_FAILURE';

export const USER_DELETE_REQUEST = '@user/USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = '@user/USER_DELETE_SUCCESS';
export const USER_DELETE_FAILURE = '@user/USER_DELETE_FAILURE';

export const USER_SET_PASSWORD_REQUEST = '@user/USER_SET_PASSWORD_REQUEST';
export const USER_SET_PASSWORD_SUCCESS = '@user/USER_SET_PASSWORD_SUCCESS';
export const USER_SET_PASSWORD_FAILURE = '@user/USER_SET_PASSWORD_FAILURE';

export const USER_REFRESH_PASSWORD_REQUEST =
  '@user/USER_REFRESH_PASSWORD_REQUEST';
export const USER_REFRESH_PASSWORD_SUCCESS =
  '@user/USER_REFRESH_PASSWORD_SUCCESS';
export const USER_REFRESH_PASSWORD_FAILURE =
  '@user/USER_REFRESH_PASSWORD_FAILURE';

export const USER_LOGIN_REQUEST = '@user/USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = '@user/USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = '@user/USER_LOGIN_FAILURE';

export const USERS_REQUEST = '@user/USERS_REQUEST';
export const USERS_SUCCESS = '@user/USERS_SUCCESS';
export const USERS_FAILURE = '@user/USERS_FAILURE';

export const USER_REQUEST = '@user/USER_REQUEST';
export const USER_SUCCESS = '@user/USER_SUCCESS';
export const USER_FAILURE = '@user/USER_FAILURE';
